// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['AnalyzePrompt'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['handlers']['AIHandler']['DeletePromptTemplate'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['handlers']['AIHandler']['DeleteProvider'](arg1);
}

export function ExplodePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['ExplodePrompt'](arg1);
}

export function GetAIConfig() {
  return window['go']['handlers']['AIHandler']['GetAIConfig']();
}

export function GetAllPromptTemplates() {
  return window['go']['handlers']['AIHandler']['GetAllPromptTemplates']();
}

export function GetAllProviders() {
  return window['go']['handlers']['AIHandler']['GetAllProviders']();
}

export function GetCurrentSettings() {
  return window['go']['handlers']['AIHandler']['GetCurrentSettings']();
}

export function GetPromptTemplate(arg1) {
  return window['go']['handlers']['AIHandler']['GetPromptTemplate'](arg1);
}

export function ImportExtractedAtoms(arg1) {
  return window['go']['handlers']['AIHandler']['ImportExtractedAtoms'](arg1);
}

export function OptimizePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['OptimizePrompt'](arg1);
}

export function ProcessAI(arg1) {
  return window['go']['handlers']['AIHandler']['ProcessAI'](arg1);
}

export function ReverseImagePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['ReverseImagePrompt'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['handlers']['AIHandler']['SaveAIConfig'](arg1);
}

export function SavePromptTemplate(arg1) {
  return window['go']['handlers']['AIHandler']['SavePromptTemplate'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['handlers']['AIHandler']['SaveProvider'](arg1);
}

export function SetCurrentPrompt(arg1) {
  return window['go']['handlers']['AIHandler']['SetCurrentPrompt'](arg1);
}

export function SetCurrentProvider(arg1) {
  return window['go']['handlers']['AIHandler']['SetCurrentProvider'](arg1);
}

export function TranslatePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['TranslatePrompt'](arg1);
}
