// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function AnalyzePrompt(arg1:handlers.AnalyzePromptRequest):Promise<handlers.AIResponse>;

export function ExplodePrompt(arg1:handlers.ExplodePromptRequest):Promise<handlers.AIResponse>;

export function GetAIConfig():Promise<handlers.AIResponse>;

export function ImportExtractedAtoms(arg1:handlers.ImportExtractedRequest):Promise<handlers.AIResponse>;

export function OptimizePrompt(arg1:handlers.OptimizePromptRequest):Promise<handlers.AIResponse>;

export function ProcessAI(arg1:handlers.GenericAIRequest):Promise<handlers.AIResponse>;

export function ReverseImagePrompt(arg1:handlers.ReverseImagePromptRequest):Promise<handlers.AIResponse>;

export function SaveAIConfig(arg1:handlers.SaveAIConfigRequest):Promise<handlers.AIResponse>;

export function TranslatePrompt(arg1:handlers.TranslatePromptRequest):Promise<handlers.AIResponse>;
