// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['AnalyzePrompt'](arg1);
}

export function ExplodePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['ExplodePrompt'](arg1);
}

export function GetAIConfig() {
  return window['go']['handlers']['AIHandler']['GetAIConfig']();
}

export function ImportExtractedAtoms(arg1) {
  return window['go']['handlers']['AIHandler']['ImportExtractedAtoms'](arg1);
}

export function OptimizePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['OptimizePrompt'](arg1);
}

export function ProcessAI(arg1) {
  return window['go']['handlers']['AIHandler']['ProcessAI'](arg1);
}

export function ReverseImagePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['ReverseImagePrompt'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['handlers']['AIHandler']['SaveAIConfig'](arg1);
}

export function TranslatePrompt(arg1) {
  return window['go']['handlers']['AIHandler']['TranslatePrompt'](arg1);
}
