// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function BatchImportAtoms(arg1:handlers.BatchImportAtomsRequest):Promise<handlers.AtomResponse>;

export function CreateAtom(arg1:handlers.CreateAtomRequest):Promise<handlers.AtomResponse>;

export function DeleteAtom(arg1:number):Promise<handlers.AtomResponse>;

export function ExportAtoms():Promise<handlers.AtomResponse>;

export function FindAtomsBySynonym(arg1:string):Promise<handlers.AtomResponse>;

export function GetAllAtomsPaginated(arg1:number,arg2:number):Promise<handlers.AtomResponse>;

export function GetAtomByID(arg1:number):Promise<handlers.AtomResponse>;

export function GetAtomsByCategory(arg1:handlers.GetAtomsByCategoryRequest):Promise<handlers.AtomResponse>;

export function GetPopularAtoms(arg1:number):Promise<handlers.AtomResponse>;

export function RecordUsage(arg1:number):Promise<handlers.AtomResponse>;

export function UpdateAtom(arg1:handlers.UpdateAtomRequest):Promise<handlers.AtomResponse>;
