// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchImportAtoms(arg1) {
  return window['go']['handlers']['AtomHandler']['BatchImportAtoms'](arg1);
}

export function CreateAtom(arg1) {
  return window['go']['handlers']['AtomHandler']['CreateAtom'](arg1);
}

export function DeleteAtom(arg1) {
  return window['go']['handlers']['AtomHandler']['DeleteAtom'](arg1);
}

export function ExportAtoms() {
  return window['go']['handlers']['AtomHandler']['ExportAtoms']();
}

export function FindAtomsBySynonym(arg1) {
  return window['go']['handlers']['AtomHandler']['FindAtomsBySynonym'](arg1);
}

export function GetAllAtomsPaginated(arg1, arg2) {
  return window['go']['handlers']['AtomHandler']['GetAllAtomsPaginated'](arg1, arg2);
}

export function GetAtomByID(arg1) {
  return window['go']['handlers']['AtomHandler']['GetAtomByID'](arg1);
}

export function GetAtomsByCategory(arg1) {
  return window['go']['handlers']['AtomHandler']['GetAtomsByCategory'](arg1);
}

export function GetPopularAtoms(arg1) {
  return window['go']['handlers']['AtomHandler']['GetPopularAtoms'](arg1);
}

export function RecordUsage(arg1) {
  return window['go']['handlers']['AtomHandler']['RecordUsage'](arg1);
}

export function UpdateAtom(arg1) {
  return window['go']['handlers']['AtomHandler']['UpdateAtom'](arg1);
}
