// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportData() {
  return window['go']['handlers']['BackupHandler']['ExportData']();
}

export function ExportToFile() {
  return window['go']['handlers']['BackupHandler']['ExportToFile']();
}

export function ExportToZip() {
  return window['go']['handlers']['BackupHandler']['ExportToZip']();
}

export function GetBackupList() {
  return window['go']['handlers']['BackupHandler']['GetBackupList']();
}

export function ImportData(arg1) {
  return window['go']['handlers']['BackupHandler']['ImportData'](arg1);
}

export function ReadBackupFile(arg1) {
  return window['go']['handlers']['BackupHandler']['ReadBackupFile'](arg1);
}
