// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function ExportData():Promise<handlers.BackupResponse>;

export function ExportToFile():Promise<handlers.BackupResponse>;

export function ExportToZip():Promise<handlers.BackupResponse>;

export function GetBackupList():Promise<handlers.BackupResponse>;

export function ImportData(arg1:handlers.ImportDataRequest):Promise<handlers.BackupResponse>;

export function ReadBackupFile(arg1:string):Promise<handlers.BackupResponse>;
