// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchAddSynonyms(arg1) {
  return window['go']['handlers']['BatchHandler']['BatchAddSynonyms'](arg1);
}

export function BatchClearCategory(arg1) {
  return window['go']['handlers']['BatchHandler']['BatchClearCategory'](arg1);
}

export function BatchDelete(arg1) {
  return window['go']['handlers']['BatchHandler']['BatchDelete'](arg1);
}

export function BatchMoveCategory(arg1) {
  return window['go']['handlers']['BatchHandler']['BatchMoveCategory'](arg1);
}

export function BatchUpdateType(arg1) {
  return window['go']['handlers']['BatchHandler']['BatchUpdateType'](arg1);
}
