// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function BatchAddSynonyms(arg1:handlers.BatchAddSynonymsRequest):Promise<handlers.BatchResponse>;

export function BatchClearCategory(arg1:handlers.BatchDeleteRequest):Promise<handlers.BatchResponse>;

export function BatchDelete(arg1:handlers.BatchDeleteRequest):Promise<handlers.BatchResponse>;

export function BatchMoveCategory(arg1:handlers.BatchMoveCategoryRequest):Promise<handlers.BatchResponse>;

export function BatchUpdateType(arg1:handlers.BatchUpdateTypeRequest):Promise<handlers.BatchResponse>;
