// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function CreateCategory(arg1:handlers.CreateCategoryRequest):Promise<handlers.CategoryResponse>;

export function DeleteCategory(arg1:number):Promise<handlers.CategoryResponse>;

export function GetCategoriesByParent(arg1:number,arg2:string):Promise<handlers.CategoryResponse>;

export function GetCategoryByID(arg1:number):Promise<handlers.CategoryResponse>;

export function GetCategoryTree(arg1:string):Promise<handlers.CategoryResponse>;

export function MoveCategory(arg1:handlers.MoveCategoryRequest):Promise<handlers.CategoryResponse>;

export function ReorderCategories(arg1:handlers.ReorderCategoriesRequest):Promise<handlers.CategoryResponse>;

export function UpdateCategory(arg1:handlers.UpdateCategoryRequest):Promise<handlers.CategoryResponse>;
