// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['handlers']['CategoryHandler']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['handlers']['CategoryHandler']['DeleteCategory'](arg1);
}

export function GetCategoriesByParent(arg1, arg2) {
  return window['go']['handlers']['CategoryHandler']['GetCategoriesByParent'](arg1, arg2);
}

export function GetCategoryByID(arg1) {
  return window['go']['handlers']['CategoryHandler']['GetCategoryByID'](arg1);
}

export function GetCategoryTree(arg1) {
  return window['go']['handlers']['CategoryHandler']['GetCategoryTree'](arg1);
}

export function MoveCategory(arg1) {
  return window['go']['handlers']['CategoryHandler']['MoveCategory'](arg1);
}

export function ReorderCategories(arg1) {
  return window['go']['handlers']['CategoryHandler']['ReorderCategories'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['handlers']['CategoryHandler']['UpdateCategory'](arg1);
}
