// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteImage(arg1) {
  return window['go']['handlers']['ImageHandler']['DeleteImage'](arg1);
}

export function GetImageByID(arg1) {
  return window['go']['handlers']['ImageHandler']['GetImageByID'](arg1);
}

export function GetImageData(arg1) {
  return window['go']['handlers']['ImageHandler']['GetImageData'](arg1);
}

export function GetImagesByPreset(arg1) {
  return window['go']['handlers']['ImageHandler']['GetImagesByPreset'](arg1);
}

export function UploadImage(arg1) {
  return window['go']['handlers']['ImageHandler']['UploadImage'](arg1);
}
