// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function DeleteImage(arg1:number):Promise<handlers.ImageResponse>;

export function GetImageByID(arg1:number):Promise<handlers.ImageResponse>;

export function GetImageData(arg1:number):Promise<handlers.ImageResponse>;

export function GetImagesByPreset(arg1:number):Promise<handlers.ImageResponse>;

export function UploadImage(arg1:handlers.UploadImageRequest):Promise<handlers.ImageResponse>;
