// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function BuildPrompt(arg1:handlers.BuildPromptRequest):Promise<handlers.PresetResponse>;

export function CleanupOldVersions(arg1:handlers.CleanupOldVersionsRequest):Promise<handlers.PresetResponse>;

export function CreatePreset(arg1:handlers.CreatePresetRequest):Promise<handlers.PresetResponse>;

export function ForkPreset(arg1:handlers.ForkPresetRequest):Promise<handlers.PresetResponse>;

export function GetCurrentWorkState(arg1:number):Promise<handlers.PresetResponse>;

export function GetPresetByID(arg1:number):Promise<handlers.PresetResponse>;

export function GetPresets(arg1:handlers.GetPresetsRequest):Promise<handlers.PresetResponse>;

export function RestorePreset(arg1:number):Promise<handlers.PresetResponse>;

export function SoftDeletePreset(arg1:number):Promise<handlers.PresetResponse>;

export function UpdatePreset(arg1:handlers.UpdatePresetRequest):Promise<handlers.PresetResponse>;
