// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildPrompt(arg1) {
  return window['go']['handlers']['PresetHandler']['BuildPrompt'](arg1);
}

export function CleanupOldVersions(arg1) {
  return window['go']['handlers']['PresetHandler']['CleanupOldVersions'](arg1);
}

export function CreatePreset(arg1) {
  return window['go']['handlers']['PresetHandler']['CreatePreset'](arg1);
}

export function ForkPreset(arg1) {
  return window['go']['handlers']['PresetHandler']['ForkPreset'](arg1);
}

export function GetCurrentWorkState(arg1) {
  return window['go']['handlers']['PresetHandler']['GetCurrentWorkState'](arg1);
}

export function GetPresetByID(arg1) {
  return window['go']['handlers']['PresetHandler']['GetPresetByID'](arg1);
}

export function GetPresets(arg1) {
  return window['go']['handlers']['PresetHandler']['GetPresets'](arg1);
}

export function RestorePreset(arg1) {
  return window['go']['handlers']['PresetHandler']['RestorePreset'](arg1);
}

export function SoftDeletePreset(arg1) {
  return window['go']['handlers']['PresetHandler']['SoftDeletePreset'](arg1);
}

export function UpdatePreset(arg1) {
  return window['go']['handlers']['PresetHandler']['UpdatePreset'](arg1);
}
