// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QuickSearch(arg1) {
  return window['go']['handlers']['SearchHandler']['QuickSearch'](arg1);
}

export function ReindexAll() {
  return window['go']['handlers']['SearchHandler']['ReindexAll']();
}

export function Search(arg1) {
  return window['go']['handlers']['SearchHandler']['Search'](arg1);
}

export function SearchAtoms(arg1) {
  return window['go']['handlers']['SearchHandler']['SearchAtoms'](arg1);
}

export function SearchPresets(arg1) {
  return window['go']['handlers']['SearchHandler']['SearchPresets'](arg1);
}
