// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function QuickSearch(arg1:string):Promise<handlers.SearchResponse>;

export function ReindexAll():Promise<handlers.SearchResponse>;

export function Search(arg1:handlers.SearchRequest):Promise<handlers.SearchResponse>;

export function SearchAtoms(arg1:handlers.SearchAtomsRequest):Promise<handlers.SearchResponse>;

export function SearchPresets(arg1:handlers.SearchPresetsRequest):Promise<handlers.SearchResponse>;
