// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultSeedData() {
  return window['go']['handlers']['SeederHandler']['GetDefaultSeedData']();
}

export function GetSeedStatus() {
  return window['go']['handlers']['SeederHandler']['GetSeedStatus']();
}

export function ImportFromJSON(arg1) {
  return window['go']['handlers']['SeederHandler']['ImportFromJSON'](arg1);
}

export function SeedAll() {
  return window['go']['handlers']['SeederHandler']['SeedAll']();
}
