// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function GetDefaultSeedData():Promise<handlers.SeederResponse>;

export function GetSeedStatus():Promise<handlers.SeederResponse>;

export function ImportFromJSON(arg1:handlers.ImportFromJSONRequest):Promise<handlers.SeederResponse>;

export function SeedAll():Promise<handlers.SeederResponse>;
