// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SplitPrompt(arg1) {
  return window['go']['handlers']['TransSessionHandler']['SplitPrompt'](arg1);
}

export function TranslateSingle(arg1) {
  return window['go']['handlers']['TransSessionHandler']['TranslateSingle'](arg1);
}

export function TranslateWords(arg1) {
  return window['go']['handlers']['TransSessionHandler']['TranslateWords'](arg1);
}
