// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function SplitPrompt(arg1:handlers.SplitPromptRequest):Promise<handlers.TransSessionResponse>;

export function TranslateSingle(arg1:handlers.TranslateSingleRequest):Promise<handlers.TransSessionResponse>;

export function TranslateWords(arg1:handlers.TranslateWordsRequest):Promise<handlers.TransSessionResponse>;
