// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function CompareVersions(arg1:number,arg2:number,arg3:number):Promise<handlers.VersionResponse>;

export function CreateVersion(arg1:handlers.CreateVersionRequest):Promise<handlers.VersionResponse>;

export function DeleteVersion(arg1:number):Promise<handlers.VersionResponse>;

export function GetLatestVersions(arg1:number,arg2:number):Promise<handlers.VersionResponse>;

export function GetStarredVersions(arg1:number):Promise<handlers.VersionResponse>;

export function GetVersion(arg1:number,arg2:number):Promise<handlers.VersionResponse>;

export function GetVersionDiffStats(arg1:number,arg2:number):Promise<handlers.VersionResponse>;

export function GetVersionHistory(arg1:number,arg2:number):Promise<handlers.VersionResponse>;

export function RollbackToVersion(arg1:number,arg2:number):Promise<handlers.VersionResponse>;

export function StarVersion(arg1:handlers.StarVersionRequest):Promise<handlers.VersionResponse>;

export function UpdateVersionPreview(arg1:handlers.UpdateVersionPreviewRequest):Promise<handlers.VersionResponse>;
