// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareVersions(arg1, arg2, arg3) {
  return window['go']['handlers']['VersionHandler']['CompareVersions'](arg1, arg2, arg3);
}

export function CreateVersion(arg1) {
  return window['go']['handlers']['VersionHandler']['CreateVersion'](arg1);
}

export function DeleteVersion(arg1) {
  return window['go']['handlers']['VersionHandler']['DeleteVersion'](arg1);
}

export function GetLatestVersions(arg1, arg2) {
  return window['go']['handlers']['VersionHandler']['GetLatestVersions'](arg1, arg2);
}

export function GetStarredVersions(arg1) {
  return window['go']['handlers']['VersionHandler']['GetStarredVersions'](arg1);
}

export function GetVersion(arg1, arg2) {
  return window['go']['handlers']['VersionHandler']['GetVersion'](arg1, arg2);
}

export function GetVersionDiffStats(arg1, arg2) {
  return window['go']['handlers']['VersionHandler']['GetVersionDiffStats'](arg1, arg2);
}

export function GetVersionHistory(arg1, arg2) {
  return window['go']['handlers']['VersionHandler']['GetVersionHistory'](arg1, arg2);
}

export function RollbackToVersion(arg1, arg2) {
  return window['go']['handlers']['VersionHandler']['RollbackToVersion'](arg1, arg2);
}

export function StarVersion(arg1) {
  return window['go']['handlers']['VersionHandler']['StarVersion'](arg1);
}

export function UpdateVersionPreview(arg1) {
  return window['go']['handlers']['VersionHandler']['UpdateVersionPreview'](arg1);
}
